baseurl = "https://seb.deleuze.fr"
title = "Sébastien Deleuze"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Sébastien Deleuze"
  info = "Spring Framework core committer, WebAssembly believer since 2016."
  description = "Sébastien Deleuze's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/profil.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sdeleuze"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 3
  url = "https://mastodon.online/@sdeleuze"
  rel = "me"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/sdeleuze"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/deleuze"
